### ISSUE TITLE
Line in the plan about exploring different subsets of the data

### ISSUE THREAD

**Issue by jrosen48** [jrosen48/comparing-sentiment#3]
super minor, but I'm confused what this line means:

https://github.com/jrosen48/comparing-sentiment/blob/266a385f5dd8c46f1642fa7278acd6e7b9d1a566/_targets.R#L33

**Comment by conradborchers** [comment]
Hey, this is just a note to myself that I wrote the analysis and descriptives functions in a way that allows us to feed any subset of the data into them. In that way, we can easily output differences between chat-sessions, non-chat tweets, etc. :)

**Comment by jrosen48** [comment]
got it, sounds good
