### ISSUE TITLE
where are raw data files saved?

### ISSUE THREAD

**Issue by jrosen48** [jrosen48/comparing-sentiment#4]
minor, where are:

- sentistrength_scale.txt
- sentistrength_binary.txt
- liwc_results.csv 

saved?

**Comment by conradborchers** [comment]
Made the data accessible to you via our secured University OneDrive, resent my mail with access details to you just now.

**Comment by conradborchers** [comment]
Not sure if this repo is private but generally I added all data files to .gitignore to comply with Twitter's user agreements

**Comment by jrosen48** [comment]
AH so sorry I remember that invite. I had the feeling I was missing _something_. 

Agree re: your use of `.gitignore`. Thanks CB
