### ISSUE TITLE
make create_raw_data faster?

### ISSUE THREAD

**Issue by jrosen48** [jrosen48/comparing-sentiment#7]
I think this pattern may be making this function slower as more files are read and merged:

https://github.com/jrosen48/comparing-sentiment/blob/00751687ec0571ae260d5da3d442c8bc825b312f/r/functions.R#L9

I think the issue is one of modifying on copy; that each time `rbind()` is called, the entire data is copied over to a new object. And so you get some kind of logarithmic (or square root) slowing in how long each iteration takes over time. [Related (see copy-on-modify)](http://adv-r.had.co.nz/Performance.html).

I wonder if an apply family function may be faster here (I have a slight preference for the {purrr} functions just because of their documentation/consistency across related functions, but I'm sure an `lapply()` or a related base function would work just fine---if it is indeed the case that a for loop is slower here.

**Comment by conradborchers** [comment]
That's something I have been looking for! Will work on this right now

**Comment by conradborchers** [comment]
Fixed it! do.call() and storing all data frames into a list did the job

**Comment by jrosen48** [comment]
w00t!
